#!/bin/bash
sleep 0.5
printf "\n"
printf "\033[1m## Approach A: Token Bucket (middleware)\033[0m\n"
printf "\n"
printf "  Express middleware with in-memory token bucket.\n"
printf "  Per-client limits keyed by API key.\n"
printf "\n"
printf "  \033[32m+\033[0m Simple, zero dependencies, ~50 lines\n"
printf "  \033[32m+\033[0m Sub-millisecond overhead\n"
printf "  \033[31m-\033[0m Single-process only (no horizontal scaling)\n"
printf "  \033[31m-\033[0m State lost on restart\n"
printf "\n"
printf "\033[1m## Approach B: Sliding Window (Redis-backed)\033[0m\n"
printf "\n"
printf "  Redis sorted sets for sliding window counters.\n"
printf "  Shared state across all instances.\n"
printf "\n"
printf "  \033[32m+\033[0m Scales horizontally\n"
printf "  \033[32m+\033[0m Survives restarts, shared across replicas\n"
printf "  \033[31m-\033[0m Redis dependency (+2-5ms per request)\n"
printf "  \033[31m-\033[0m More complex (Lua scripts for atomicity)\n"
printf "\n"
printf "  \033[1;36m→\033[0m \033[1mRecommendation:\033[0m Approach B — you mentioned\n"
printf "    multi-instance deployment is planned for Q2.\n"
printf "\n"
