/**
 * CI `skills:guard` check — detects drift between `content/` sources
 * and the committed `skills/` generated tree.
 *
 * Runs `buildAllSkills()` in-process against the project root, then
 * invokes `git diff --exit-code skills/`. A non-empty diff means either:
 *
 *   1. A developer changed `content/` but forgot to run
 *      `npm run build:skills` and commit the regenerated output, or
 *   2. A developer hand-edited a generated file under `skills/`
 *      (which the build has just overwritten).
 *
 * Either way the guard fails with a remediation message pointing at
 * `npm run build:skills`.
 *
 * Exported `runSkillsGuard()` is testable — tests hand it a temp
 * project root. The CLI at the bottom of this file wires it to
 * `process.cwd()` / `process.exit()`.
 *
 * Implements: DR-1 (guard), DR-10 (stale-output path).
 */

import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { runCommandSync } from '../utils/process.js';
import { buildAllSkills } from './build-skills.js';
import { emitCommandAliases } from './build-command-aliases.js';
import { emitAuthoredArtifacts } from './build-authored-artifacts.js';
import { resolveMainDeps, type MainDeps } from './cli-helpers.js';

/**
 * Outcome of a guard run. `ok === true` means the generated tree was
 * in sync with HEAD; `ok === false` means either the build itself
 * failed or `git diff skills/` produced output.
 *
 * `message` is a human-readable explanation safe to print in CI logs.
 * On success it names what was checked; on failure it includes the
 * remediation command and, where possible, the raw diff body so the
 * drifted file paths are visible.
 */
export interface SkillsGuardResult {
  ok: boolean;
  exitCode: number;
  message: string;
}

/**
 * Injectable collaborators so tests can avoid touching the real
 * filesystem or process state. Production leaves these undefined and
 * the implementation defaults to the obvious real-world behavior.
 *
 * `regenerateAgents` exists because the agents tree is generated by a
 * separate entry point (`src/runtime/agents/generate-agents.ts`)
 * that lives outside this package's `rootDir`. Production defaults to
 * spawning that entry point as a child process via tsx — the same way
 * `npm run generate:agents` does. Tests inject a deterministic
 * synchronous writer so the temp-sandbox path does not need to drag
 * in the full adapter registry.
 */
export interface SkillsGuardOptions {
  cwd: string;
  regenerateAgents?: (cwd: string) => void;
}

/**
 * Fixed remediation string. Exported-shaped via the returned message
 * so tests can assert the command is mentioned verbatim. Kept as a
 * const so a future refactor (e.g. a shared CLI message helper) can
 * reuse it from one place.
 */
const REMEDIATION =
  "Generated skills are stale. Run 'npm run build:skills' and commit the result.";

/**
 * Same shape as `REMEDIATION` but for the `agents/` drift path. The
 * developer remediation is a single command (`npm run generate:agents`)
 * because the agents tree is generated independently of the skills
 * renderer; chaining the two would conflate failure modes.
 */
const REMEDIATION_AGENTS =
  "Generated agents are stale. Run 'npm run generate:agents' and commit the result.";

/**
 * Remediation for the `command-aliases/` drift path (T4, #1472). The
 * generated alias tree is produced by the same `npm run build:skills`
 * pass that renders `skills/` (the build entry point calls
 * `emitCommandAliases` after `buildAllSkills`), so the fix is identical:
 * rebuild and commit. Kept distinct from `REMEDIATION` only so the
 * failure header names the alias tree, not skills.
 */
const REMEDIATION_ALIASES =
  "Generated command aliases are stale. Run 'npm run build:skills' and commit the result.";

/**
 * Remediation for the flat `commands/` and `rules/` trees. These became
 * generator output when their sources moved under `content/<domain>/`, so an
 * edit made directly to the flat tree is silently discarded by the next build.
 * Guarding them is what turns that discard into a red signal.
 */
const REMEDIATION_AUTHORED =
  "Generated commands/ or rules/ are stale, or were edited directly instead of " +
  "under content/<domain>/. Run 'npm run build:skills' and commit the result.";

/**
 * Default production regenerator. Spawns `tsx` against
 * `src/runtime/agents/generate-agents.ts` with `cwd` as
 * the output root — mirroring how `npm run generate:agents` invokes
 * the same entry point. We resolve the script path relative to `cwd`
 * because the only callers in production hand us the repo root.
 *
 * Throws on subprocess failure; the surrounding guard wraps the
 * exception into a structured `SkillsGuardResult`.
 */
function defaultRegenerateAgents(cwd: string): void {
  const scriptPath = join(cwd, 'src', 'runtime', 'agents', 'generate-agents.ts');
  // `runCommandSync`, not `execFileSync`: `npx` is a .cmd shim on Windows and
  // execFile cannot launch one (#1623). This module only came under the lint
  // that enforces it when task 019 folded the installer into the linted tree.
  runCommandSync('npx', ['tsx', scriptPath, cwd], {
    cwd,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

/**
 * Run the build and verify the generated `skills/` tree matches what
 * is committed in git. Does not modify anything outside `opts.cwd`
 * and does not call `process.exit` — the CLI wrapper at the bottom
 * of this file is responsible for exit handling.
 *
 * ### Determinism contract
 *
 * The guard's correctness relies on `buildAllSkills()` being a pure
 * function of `(content/, content/harness/runtimes/*.yaml)`: running it twice on
 * identical inputs must produce byte-identical output. Two specific
 * rendering paths need to uphold this:
 *
 *   1. **Placeholder substitution** (`render()`): deterministic by
 *      construction — `PLACEHOLDER_REGEX.replace()` visits tokens in
 *      source order and looks up values from a static map.
 *
 *   2. **CALL macro expansion** (`renderCallMacros()`): emits either
 *      `JSON.stringify(args, null, 2)` (MCP facade) or
 *      `--{kebab-key} {value}` pairs in `Object.entries` order (CLI
 *      facade). Both rely on V8 preserving object-key insertion order,
 *      which is guaranteed by the ECMAScript spec for string keys. The
 *      args object is assembled with a fixed key order (the `action`
 *      discriminator first, then `...ast.args` from `JSON.parse`, which
 *      itself preserves source-text key order).
 *
 * If either invariant is ever broken (e.g. a future refactor switches
 * to `Object.keys().sort()` non-idempotently, or swaps
 * `JSON.stringify` for a reflection-based pretty-printer), this guard
 * will start false-positiving on rebuilds. The
 * `SkillsGuard_AfterCallMacroRender_NoDrift` test in
 * `skills-guard.test.ts` locks the CALL-macro determinism invariant in
 * place.
 *
 * @param opts.cwd - Absolute path to the project root. Must contain
 *   `content/`, `content/harness/runtimes/`, and a git repo whose HEAD tracks the
 *   current state of `skills/`.
 */
export function runSkillsGuard(opts: SkillsGuardOptions): SkillsGuardResult {
  const { cwd } = opts;
  const regenerateAgents = opts.regenerateAgents ?? defaultRegenerateAgents;

  // Aggregate failures across both checks rather than fail-fast on the
  // first. A developer who hand-edited *both* a skill and an agent
  // file will see both paths in one CI run, not chase a second
  // failure after fixing the first.
  const failures: string[] = [];

  // ─── Skills check ─────────────────────────────────────────────────

  // Step 1a: regenerate `skills/`. A build failure is a guard failure
  // because CI must not pass if the source tree can't even render.
  let skillsBuildFailed = false;
  try {
    buildAllSkills({
      srcDir: join(cwd, 'content'),
      outDir: join(cwd, 'skills'),
      runtimesDir: join(cwd, 'content/harness/runtimes'),
    });
  } catch (err) {
    skillsBuildFailed = true;
    const detail = err instanceof Error ? err.message : String(err);
    failures.push(`[skills:guard] build failed: ${detail}\n${REMEDIATION}`);
  }

  // Step 1b: diff the generated skills tree vs HEAD. Skip only if the build
  // itself failed (no point reporting drift against a half-rendered tree).
  //
  // Since the renderer split (DR-1), `skills/` spans two logical trees that
  // are diffed as separate, non-overlapping checks so a failure attributes to
  // the right one:
  //   - `skills/standard/`         the single procedural render (DR-1)
  //   - `skills/` minus standard   the per-runtime orchestration residual (DR-2)
  // Drift in EITHER fails the guard. The residual check uses a git pathspec
  // exclusion so a standard-only drift is reported once (by the standard
  // check), not twice.
  if (!skillsBuildFailed) {
    const standardDiff = checkGitDiff(
      cwd,
      'skills/standard/',
      REMEDIATION,
      'skills/standard',
    );
    if (standardDiff !== null) failures.push(standardDiff);

    const residualDiff = checkGitDiff(
      cwd,
      ['skills/', ':(exclude)skills/standard/'],
      REMEDIATION,
      'skills (orchestration residual)',
    );
    if (residualDiff !== null) failures.push(residualDiff);
  }

  // ─── Authored flat-tree check (commands/, rules/) ─────────────────

  // Regenerated before the alias check below, which reads the flat
  // `commands/` tree this pass produces. Same reasoning as the aliases: the
  // committed tree would always match an un-regenerated copy of itself, so
  // the guard has to rebuild before it diffs.
  let authoredBuildFailed = false;
  try {
    emitAuthoredArtifacts({ contentDir: join(cwd, 'content'), outRoot: cwd });
  } catch (err) {
    authoredBuildFailed = true;
    const detail = err instanceof Error ? err.message : String(err);
    failures.push(
      `[skills:guard] authored-artifact emission failed: ${detail}\n${REMEDIATION_AUTHORED}`,
    );
  }

  if (!authoredBuildFailed) {
    for (const tree of ['commands', 'rules']) {
      const diff = checkGitDiff(cwd, `${tree}/`, REMEDIATION_AUTHORED, tree);
      if (diff !== null) failures.push(diff);
    }
  }

  // ─── Command-aliases check (T4, #1472) ────────────────────────────

  // The generated `command-aliases/**` tree is a build artifact like
  // `skills/`, but it is emitted by `emitCommandAliases` — a step the
  // build entry point runs *after* `buildAllSkills`, NOT by
  // `buildAllSkills` itself. So the guard must regenerate it here before
  // diffing; widening the diff scope alone would never catch drift
  // because the committed tree would always match an un-regenerated copy
  // of itself. A contributor who edits a `commands/*.md` description or
  // the `COMMAND_TO_SKILL` map without rebuilding gets a red signal here.
  let aliasesBuildFailed = false;
  try {
    emitCommandAliases({
      runtimesDir: join(cwd, 'content/harness/runtimes'),
      commandsDir: join(cwd, 'commands'),
      outDir: join(cwd, 'command-aliases'),
    });
  } catch (err) {
    aliasesBuildFailed = true;
    const detail = err instanceof Error ? err.message : String(err);
    failures.push(
      `[skills:guard] command-alias emission failed: ${detail}\n${REMEDIATION_ALIASES}`,
    );
  }

  if (!aliasesBuildFailed) {
    const aliasesDiff = checkGitDiff(
      cwd,
      'command-aliases/',
      REMEDIATION_ALIASES,
      'command-aliases',
    );
    if (aliasesDiff !== null) failures.push(aliasesDiff);
  }

  // ─── Agents check ─────────────────────────────────────────────────

  // Step 2a: regenerate `agents/`. Same failure semantics as the
  // skills build — a regeneration failure is a guard failure.
  let agentsBuildFailed = false;
  try {
    regenerateAgents(cwd);
  } catch (err) {
    agentsBuildFailed = true;
    const detail =
      getExecErrorStderr(err) ||
      (err instanceof Error ? err.message : String(err));
    failures.push(
      `[skills:guard] generate-agents failed: ${detail}\n${REMEDIATION_AGENTS}`,
    );
  }

  // Step 2b: diff every agent output tree vs HEAD. Same skip rule as
  // the skills diff — only run if the regeneration itself succeeded.
  //
  // The adapter list (`src/runtime/agents/adapters/`)
  // writes agents into five distinct trees per runtime. Checking only
  // `agents/` (Claude) lets stale Codex/Cursor/OpenCode/Copilot files
  // slip through CI (Sentry #1181 HIGH). The pathspecs below mirror
  // each adapter's `agentFilePath()` directory prefix:
  //   - claude.ts   → agents/<id>.md
  //   - codex.ts    → .codex/agents/<id>.toml
  //   - cursor.ts   → .cursor/agents/<id>.md
  //   - opencode.ts → .opencode/agents/<id>.md
  //   - copilot.ts  → .github/agents/<id>.agent.md
  // When a new runtime adapter lands, add its agent dir here.
  if (!agentsBuildFailed) {
    const agentsDiff = checkGitDiff(
      cwd,
      [
        'agents/',
        '.codex/agents/',
        '.cursor/agents/',
        '.opencode/agents/',
        '.github/agents/',
      ],
      REMEDIATION_AGENTS,
      'agents',
    );
    if (agentsDiff !== null) failures.push(agentsDiff);
  }

  // ─── Aggregate ────────────────────────────────────────────────────

  if (failures.length > 0) {
    return {
      ok: false,
      exitCode: 1,
      message: failures.join('\n\n'),
    };
  }

  return {
    ok: true,
    exitCode: 0,
    message:
      '[skills:guard] skills/, command-aliases/ and agents/ are in sync with sources',
  };
}

/**
 * Run `git diff --exit-code -- <pathspec>` against `cwd` and return:
 *   - `null` if the tree is clean (exit 0)
 *   - a formatted failure message if drift is detected (exit 1)
 *   - a formatted environment-error message for any other exit
 *
 * Pulled out so both the `skills/` and `agents/` paths share the same
 * exit-code narrowing, output capture, and message formatting. The
 * `label` argument names the tree in the failure header so a developer
 * scanning CI output can tell at a glance which check fired.
 */
function checkGitDiff(
  cwd: string,
  pathspec: string | readonly string[],
  remediation: string,
  label: string,
): string | null {
  const pathspecs = typeof pathspec === 'string' ? [pathspec] : [...pathspec];
  try {
    execFileSync('git', ['diff', '--exit-code', '--', ...pathspecs], {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return null;
  } catch (err) {
    // `git diff --exit-code` with a non-empty diff exits 1. Node's
    // `execFileSync` treats any non-zero exit as a throw, attaching
    // the captured stdout/stderr to the error. The type of that
    // error is loose, so we narrow with a structured guard rather
    // than a cast to `any`.
    const status = getExecErrorStatus(err);
    const stdout = getExecErrorStdout(err);
    const stderr = getExecErrorStderr(err);

    if (status === 1) {
      return [
        `[skills:guard] generated ${label} tree is stale (drift detected).`,
        remediation,
        '',
        'Diff:',
        stdout.length > 0 ? stdout : '(no diff output captured)',
      ].join('\n');
    }

    // Any other exit (typically 128 = not a git repo, bad path, etc.)
    // is an unrecoverable environment problem. Surface everything we
    // have so the CI operator can debug.
    return [
      `[skills:guard] git diff failed for ${label}/ (exit ${status ?? 'unknown'})`,
      stderr || stdout || String(err),
      remediation,
    ].join('\n');
  }
}

/**
 * Narrow `unknown` to extract the exit status of a failed
 * `execFileSync` call without reaching for `any`. Node's child_process
 * errors carry a numeric `status` property when the process exited
 * normally with a non-zero code.
 */
function getExecErrorStatus(err: unknown): number | null {
  if (typeof err === 'object' && err !== null && 'status' in err) {
    const status = (err as { status: unknown }).status;
    if (typeof status === 'number') return status;
  }
  return null;
}

/** Same narrowing pattern for `stdout`. */
function getExecErrorStdout(err: unknown): string {
  if (typeof err === 'object' && err !== null && 'stdout' in err) {
    const out = (err as { stdout: unknown }).stdout;
    if (Buffer.isBuffer(out)) return out.toString('utf8');
    if (typeof out === 'string') return out;
  }
  return '';
}

/** Same narrowing pattern for `stderr`. */
function getExecErrorStderr(err: unknown): string {
  if (typeof err === 'object' && err !== null && 'stderr' in err) {
    const out = (err as { stderr: unknown }).stderr;
    if (Buffer.isBuffer(out)) return out.toString('utf8');
    if (typeof out === 'string') return out;
  }
  return '';
}

// -----------------------------------------------------------------------------
// CLI entry (`npm run skills:guard`)
// -----------------------------------------------------------------------------

/**
 * Re-export of the shared `MainDeps` shape so a future refactor of
 * this file's callers does not need to chase a second import line.
 * Canonical definition lives in `cli-helpers.ts`.
 */
export type { MainDeps } from './cli-helpers.js';

/**
 * `npm run skills:guard` entry point. Invokes `runSkillsGuard` against
 * `deps.cwd()` and exits with the returned code after printing the
 * result message. Success prints to stdout; failure to stderr.
 */
export function main(_argv: string[], deps: MainDeps = {}): void {
  const { cwd, exit, log, errLog } = resolveMainDeps(deps);

  const result = runSkillsGuard({ cwd: cwd() });

  if (result.ok) {
    log(result.message);
  } else {
    errLog(result.message);
  }
  exit(result.exitCode);
}

// Self-invocation guard: only run `main()` when this file is executed
// directly (e.g. `node dist/skills-guard.js`). Importing it from a
// test must NOT trigger a guard run.
if (import.meta.url === `file://${process.argv[1]}`) {
  main(process.argv.slice(2));
}
