/**
 * Context Economy checker — pure TypeScript port of check-context-economy.sh.
 *
 * Analyzes a unified diff for code complexity patterns that impact LLM context
 * consumption: oversized files, wide diffs, and large generated files.
 *
 * Operates in diff-only mode (no filesystem access required).
 */

/** Severity levels for findings. */
export type Severity = 'HIGH' | 'MEDIUM' | 'LOW';

/** A single context-economy finding. */
export interface ContextEconomyFinding {
  readonly severity: Severity;
  readonly message: string;
}

/** Result of running the context-economy checks. */
export interface ContextEconomyResult {
  /** Whether all checks passed (no findings). */
  readonly pass: boolean;
  /** Total number of checks that were executed. */
  readonly checksRun: number;
  /** Number of checks that passed without findings. */
  readonly checksPassed: number;
  /** Individual findings, empty when pass === true. */
  readonly findings: readonly ContextEconomyFinding[];
}

// ============================================================
// Internal: diff parsing
// ============================================================

interface ParsedFile {
  readonly name: string;
  readonly addedLines: readonly string[];
}

/**
 * Parse a unified diff into per-file added-line arrays.
 *
 * Only lines starting with `+` (excluding `+++` header lines) are counted
 * as added lines.
 */
function parseDiff(diff: string): ParsedFile[] {
  const files: ParsedFile[] = [];
  let currentName = '';
  let currentAdded: string[] = [];

  for (const line of diff.split('\n')) {
    const headerMatch = line.match(/^diff --git a\/(.+?) b\//);
    if (headerMatch) {
      // Flush previous file
      if (currentName) {
        files.push({ name: currentName, addedLines: currentAdded });
      }
      currentName = headerMatch[1];
      currentAdded = [];
      continue;
    }

    // Skip +++ header lines (e.g. "+++ b/file.ts")
    if (line.startsWith('+++ ')) {
      continue;
    }

    // Count added lines (all lines starting with +, header already filtered)
    if (line.startsWith('+')) {
      currentAdded.push(line.slice(1));
    }
  }

  // Flush last file
  if (currentName) {
    files.push({ name: currentName, addedLines: currentAdded });
  }

  return files;
}

/** Check if a file is a TypeScript or JavaScript source file. */
function isSourceFile(name: string): boolean {
  return name.endsWith('.ts') || name.endsWith('.js');
}

// ============================================================
// Individual checks
// ============================================================

const SOURCE_FILE_LENGTH_THRESHOLD = 400;
const DIFF_BREADTH_THRESHOLD = 30;
const GENERATED_FILE_THRESHOLD = 1000;

const GENERATED_MARKERS_RE =
  /@generated|AUTO-GENERATED|eslint-disable|auto[- ]?generated|do not edit|generated by|this file is generated|machine generated/i;

/**
 * Check 1: Source file length (>400 added lines for .ts/.js files).
 */
function checkSourceFileLength(files: readonly ParsedFile[]): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  const findings: ContextEconomyFinding[] = [];

  for (const file of files) {
    if (!isSourceFile(file.name)) continue;
    if (file.addedLines.length > SOURCE_FILE_LENGTH_THRESHOLD) {
      findings.push({
        severity: 'MEDIUM',
        message: `\`${file.name}\` — Source file exceeds 400 lines (${file.addedLines.length} added lines)`,
      });
    }
  }

  return { findings, passed: findings.length === 0 };
}

/**
 * Check 2: Function/method length — skipped in diff-only mode.
 *
 * The bash script only performs this check in --repo-root mode because it
 * requires access to actual files for brace-counting. In the pure-diff
 * TypeScript port we always pass this check.
 */
function checkFunctionLength(): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  return { findings: [], passed: true };
}

/**
 * Check 3: Diff breadth (>30 files changed).
 */
function checkDiffBreadth(files: readonly ParsedFile[]): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  const findings: ContextEconomyFinding[] = [];

  if (files.length > DIFF_BREADTH_THRESHOLD) {
    findings.push({
      severity: 'MEDIUM',
      message: `Diff breadth: ${files.length} files changed (threshold: ${DIFF_BREADTH_THRESHOLD})`,
    });
  }

  return { findings, passed: findings.length === 0 };
}

/**
 * Check 4: Large generated files (>1000 added lines with markers).
 *
 * In diff-only mode:
 * - If a generated marker is detected AND there are added lines -> finding (LOW)
 * - If >1000 added lines without marker -> "possible generated file" (LOW)
 */
function checkLargeGeneratedFiles(files: readonly ParsedFile[]): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  const findings: ContextEconomyFinding[] = [];

  for (const file of files) {
    const hasMarker = file.addedLines.some((line) =>
      GENERATED_MARKERS_RE.test(line),
    );
    const addedCount = file.addedLines.length;

    if (hasMarker && addedCount > 0) {
      findings.push({
        severity: 'LOW',
        message: `\`${file.name}\` — Generated file detected in diff (${addedCount} added lines)`,
      });
    } else if (addedCount > GENERATED_FILE_THRESHOLD) {
      findings.push({
        severity: 'LOW',
        message: `\`${file.name}\` — ${addedCount} added lines (possible generated file, threshold: ${GENERATED_FILE_THRESHOLD})`,
      });
    }
  }

  return { findings, passed: findings.length === 0 };
}

// ============================================================
// Public API
// ============================================================

/**
 * Run all context-economy checks on a unified diff string.
 *
 * @param diff - A unified diff string (as produced by `git diff`).
 * @returns The aggregated check result.
 */
export function checkContextEconomy(diff: string): ContextEconomyResult {
  if (!diff.trim()) {
    return { pass: true, checksRun: 0, checksPassed: 0, findings: [] };
  }

  const files = parseDiff(diff);

  // Function-length check requires filesystem access (brace-counting) and is
  // skipped in diff-only mode — not counted in checksRun/checksPassed.
  const checks = [
    checkSourceFileLength(files),
    checkDiffBreadth(files),
    checkLargeGeneratedFiles(files),
  ];

  const allFindings = checks.flatMap((c) => c.findings);
  const passed = checks.filter((c) => c.passed).length;

  return {
    pass: allFindings.length === 0,
    checksRun: checks.length,
    checksPassed: passed,
    findings: allFindings,
  };
}
