/**
 * A retired action name stays retired, on every surface that publishes one.
 *
 * Removing a registered action name is a contract change, not an internal edit:
 * the name is a CLI subcommand, a tool-description advertisement, and — for a
 * view — a projection registration and a `--follow` target. Those surfaces are
 * separately maintained lists, so a retirement removes the name from four or
 * five places and a later change can put it back in one of them without
 * anything noticing. A half-present name is worse than either state: the CLI
 * advertises a subcommand whose router answers `UNKNOWN_ACTION`.
 *
 * The retired set is DATA. A future retirement adds a row and inherits every
 * surface check; a surface added later is wired in once, here, and every past
 * retirement is checked against it retroactively.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { lexModule } from '../../tools/test-helpers/module-lexer.js';
import { TOOL_REGISTRY } from '../../src/registry.js';
import { BUILTIN_VIEW_NAMES } from '../../src/projections/views/registry.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

/** Where the CLI declares which view actions get a `--follow` flag. */
const CLI_MODULE = 'src/adapters/cli/cli.ts';

/**
 * The GENERATED addressing set of the compiled contract surface.
 *
 * Read as source rather than imported for the same reason as the module above,
 * and included because it is the surface that actually went stale: the compiled
 * artifacts are regenerated by a separate gesture from the declaration edit, so
 * a retirement that never re-ran it ships a client that can still address the
 * dead name.
 */
const ACTION_IDS_MODULE = 'src/contract/cli/generated/cli-action-ids.ts';

function cliActionIds(): string[] {
  const { commentMaskedSource } = lexModule(
    readFileSync(path.join(REPO_ROOT, ACTION_IDS_MODULE), 'utf8'),
    path.basename(ACTION_IDS_MODULE),
  );
  const declaration = /CLI_ACTION_IDS[^=]*=\s*\[([^\]]*)\]/.exec(commentMaskedSource);
  if (!declaration?.[1]) return [];
  return [...declaration[1].matchAll(/'([^']+)'/g)].map((match) => match[1]!);
}

interface Retired {
  /** The composite tool the action was registered on. */
  readonly tool: string;
  /** The action name, as a client would have typed it. */
  readonly name: string;
  /** Also a projection / `--follow` target, so the view-only surfaces apply. */
  readonly wasAView: boolean;
  /** Why it went, in one line — the record a reviewer reads before re-adding it. */
  readonly why: string;
}

const ORCH = 'exarchos_orchestrate';

const RETIRED: readonly Retired[] = [
  {
    tool: 'exarchos_view',
    name: 'convergence',
    wasAView: true,
    why:
      'Attributed a gate result by reading `details.dimension`, which the durable gate ' +
      'runner never stamps. Both gates on D2 run through that runner, so D2 could never ' +
      'converge and the aggregate verdict was unsatisfiable on any automated path.',
  },
  {
    tool: ORCH,
    name: 'check_convergence',
    wasAView: false,
    why:
      'The view above read this gate. Retired for the same reason and in the same change: ' +
      'its D2 arm keyed on a dimension no producer stamps, so its verdict was false on ' +
      'every input. `gate.dimension` itself is kept — only this consumer goes.',
  },
  {
    tool: ORCH,
    name: 'check_coverage_thresholds',
    wasAView: false,
    why:
      'Read Istanbul/Jest `coverage-summary.json` shapes directly — the toolchain literal ' +
      'this wave exists to remove — and no runbook chain or resolver sequence reached it, ' +
      'so it declared an obligation it was never asked to discharge.',
  },
  {
    tool: ORCH,
    name: 'check_design_completeness',
    wasAView: false,
    why:
      'A self-declared deprecated alias that delegated to `check_plan_coverage`. Deleted ' +
      'outright rather than left deprecated, so the plan-structure binding has one name ' +
      'for the obligation instead of two.',
  },
  {
    tool: ORCH,
    name: 'check_context_economy',
    wasAView: false,
    why:
      'One of exactly three `getDiff` callers among the gates, measured and found ' +
      'structurally identical to the other two. Consolidated into `check_diff_hygiene`, ' +
      'which emits one durable row per rule under each rule\'s own name and dimension.',
  },
  {
    tool: ORCH,
    name: 'check_operational_resilience',
    wasAView: false,
    why:
      'The second of the three `getDiff` callers. Consolidated into `check_diff_hygiene` ' +
      'as a rule in the pack; the rule keeps its own gate name and dimension on the ' +
      'durable row, so the D-axis it reported is preserved.',
  },
  {
    tool: ORCH,
    name: 'check_workflow_determinism',
    wasAView: false,
    why:
      'The third of the three `getDiff` callers. Consolidated into `check_diff_hygiene` ' +
      'as a rule in the pack, on the same terms as the two above.',
  },
  {
    tool: ORCH,
    name: 'pre_synthesis_check',
    wasAView: false,
    why:
      'A blocking gate nothing invoked. Folded INTO `prepare_synthesis`, carrying its ' +
      'resolver and provider seams across, so the checks still run — on the path that is ' +
      'actually reached rather than on one that never was.',
  },
  {
    tool: ORCH,
    name: 'debug_review_gate',
    wasAView: false,
    why:
      'Held the last `npm run test:run` literal in the gate population and no chain ' +
      'reached it. Deleted rather than wired, on the operator decision recorded in the ' +
      'spec, closing the literal and the orphan in one move.',
  },
];

/**
 * The members of `VIEW_FOLLOW_ACTIONS`, read from the CLI module's SOURCE.
 *
 * Importing the module would be more direct, but this tier has no `bun:sqlite`
 * alias and the CLI's transitive graph reaches the SQLite backend. The set is a
 * flat literal, so lexing it is exact; `commentMaskedSource` keeps the string
 * literals and blanks the comments, so the prose above the declaration — which
 * names its members — cannot answer for the declaration.
 */
function viewFollowActions(): string[] {
  const { commentMaskedSource } = lexModule(
    readFileSync(path.join(REPO_ROOT, CLI_MODULE), 'utf8'),
    path.basename(CLI_MODULE),
  );
  const declaration = /VIEW_FOLLOW_ACTIONS[^=]*=\s*new Set\(\[([^\]]*)\]\)/.exec(commentMaskedSource);
  if (!declaration?.[1]) return [];
  return [...declaration[1].matchAll(/'([^']+)'/g)].map((match) => match[1]!);
}

/** Parse the `Actions: a, b, c` advertisement out of a tool description. */
function advertisedActions(slimDescription: string | undefined): string[] {
  const match = /Actions:\s*(.+)$/s.exec(slimDescription ?? '');
  if (!match?.[1]) return [];
  return match[1].split(',').map((entry) => entry.trim()).filter(Boolean);
}

describe('retired public names', () => {
  it('RetiredActionNames_AreRemovedFromEveryPublishedSurface', () => {
    // The denominator, five times over: an empty retired set would make the loop
    // pass by never running, and an empty surface would make each `not.toContain`
    // trivially true against a list that failed to load.
    expect(RETIRED.length, 'the retired set is empty — this guard governs nothing').toBeGreaterThan(0);
    expect(BUILTIN_VIEW_NAMES.size, 'BUILTIN_VIEW_NAMES is empty').toBeGreaterThan(10);
    const followActions = viewFollowActions();
    expect(
      followActions.length,
      `VIEW_FOLLOW_ACTIONS could not be read out of ${CLI_MODULE} — the declaration moved ` +
        'or changed shape, so the surface check below is inert',
    ).toBeGreaterThan(1);
    expect(TOOL_REGISTRY.length, 'the registry is empty').toBeGreaterThan(0);
    const actionIds = cliActionIds();
    expect(
      actionIds.length,
      `CLI_ACTION_IDS could not be read out of ${ACTION_IDS_MODULE} — the declaration moved ` +
        'or changed shape, so the addressing check below is inert',
    ).toBeGreaterThan(50);

    for (const { tool, name, wasAView, why } of RETIRED) {
      expect(why.length, `${tool}.${name} is retired with no stated reason`).toBeGreaterThan(40);

      const composite = TOOL_REGISTRY.find((entry) => entry.name === tool);
      expect(composite, `${tool} is not registered, so this row checks nothing`).toBeDefined();

      // 1. The registry — what `describe(actions)` and the CLI command tree
      //    are both projections of.
      expect(
        composite!.actions.map((action) => action.name),
        `${tool} still registers the retired action \`${name}\``,
      ).not.toContain(name);

      // 2. The tool-description advertisement. Nothing derives it from the
      //    registry, so it is the surface most likely to keep a dead name.
      expect(
        advertisedActions(composite!.slimDescription),
        `${tool}'s slimDescription still advertises \`${name}\``,
      ).not.toContain(name);

      // 3. The compiled addressing set. It is generated from the declarations,
      //    but by a SEPARATE gesture from editing them, so a retirement that
      //    never re-ran the generator ships a client that can still address a
      //    name the router answers `UNKNOWN_ACTION` for.
      expect(
        actionIds,
        `${ACTION_IDS_MODULE} still addresses \`${tool}.${name}\` — regenerate the ` +
          'compiled contract artifacts',
      ).not.toContain(`${tool}.${name}`);

      if (!wasAView) continue;

      // 4. The projection name space. A name left here reserves it against
      //    custom views while nothing serves it.
      expect(
        [...BUILTIN_VIEW_NAMES],
        `BUILTIN_VIEW_NAMES still reserves \`${name}\``,
      ).not.toContain(name);

      // 5. The `--follow` set. A member here gets a `--follow` flag registered
      //    on a subcommand that no longer exists.
      expect(
        followActions,
        `VIEW_FOLLOW_ACTIONS still lists \`${name}\` as a pollable view`,
      ).not.toContain(name);
    }
  });
});
