// ─── Diff corpus for the diff-hygiene characterization ──────────────────────
//
// One named diff per behaviour the three folded gates could exhibit, plus the
// combinations that made them disagree with each other. The consolidation is
// only safe if the new gate answers identically on every one of these, so the
// corpus is the denominator of that claim and is asserted non-trivial by the
// suite that reads it.
//
// The diffs are BUILT rather than pasted so a threshold case says which side of
// the threshold it is on.
// ─────────────────────────────────────────────────────────────────────────────

function fileDiff(name: string, addedLines: readonly string[]): string {
  return [
    `diff --git a/${name} b/${name}`,
    '--- /dev/null',
    `+++ b/${name}`,
    '@@ -0,0 +1,' + String(addedLines.length) + ' @@',
    ...addedLines.map((line) => `+${line}`),
    '',
  ].join('\n');
}

function repeat(line: string, count: number): string[] {
  return Array.from({ length: count }, (_, index) => `${line} // ${String(index)}`);
}

/** Every corpus entry, keyed by the behaviour it exercises. */
export const DIFF_CORPUS: Readonly<Record<string, string>> = Object.freeze({
  /** Nothing at all: every checker's short-circuit. */
  empty: '',

  /** Whitespace only — still nothing, and the trim guard must agree. */
  blank: '   \n\t\n',

  /** A small, clean source file: the all-pass baseline. */
  cleanSource: fileDiff('src/clean.ts', [
    'export function add(a: number, b: number): number {',
    '  return a + b;',
    '}',
  ]),

  /** 401 added lines in a .ts file: one over the source-length threshold. */
  oversizeSource: fileDiff('src/huge.ts', repeat('const value = 1;', 401)),

  /** 400 added lines exactly: the threshold is exclusive, so this must pass. */
  atSourceLengthThreshold: fileDiff('src/exactly-four-hundred.ts', repeat('const value = 1;', 400)),

  /** 31 files: one over the breadth threshold. */
  wideDiff: Array.from({ length: 31 }, (_, index) =>
    fileDiff(`src/mod-${String(index)}.ts`, ['export const x = 1;']),
  ).join(''),

  /** 30 files exactly: at the breadth threshold, which must not fire. */
  atBreadthThreshold: Array.from({ length: 30 }, (_, index) =>
    fileDiff(`src/edge-${String(index)}.ts`, ['export const x = 1;']),
  ).join(''),

  /** A generated-file marker with a tiny body. */
  generatedMarker: fileDiff('src/generated/client.ts', [
    '// @generated by the schema compiler — do not edit',
    'export const VERSION = 1;',
  ]),

  /** 1001 added lines with no marker: the "possible generated file" arm. */
  bulkWithoutMarker: fileDiff('data/table.json', repeat('  "key": "value",', 1001)),

  /** An empty catch block. */
  emptyCatch: fileDiff('src/handler.ts', [
    'export function run(): void {',
    '  try {',
    '    work();',
    '  } catch (err) {}',
    '}',
  ]),

  /** A catch that neither rethrows, logs, returns an error nor rejects. */
  swallowedError: fileDiff('src/service.ts', [
    'export function run(): void {',
    '  try {',
    '    work();',
    '  } catch (err) {',
    '    recovered = true;',
    '  }',
    '}',
  ]),

  /** console.log in a non-test source file. */
  consoleLogInSource: fileDiff('src/trace.ts', [
    'export function trace(): void {',
    '  console.log("here");',
    '}',
  ]),

  /** console.log in a test file: excluded from the source rule, caught by the test rule. */
  consoleLogInTest: fileDiff('src/trace.test.ts', [
    'it("works", () => {',
    '  console.log("here");',
    '});',
  ]),

  /** while(true) with no bound in reach. */
  unboundedRetry: fileDiff('src/poller.ts', [
    'export function poll(): void {',
    '  while (true) {',
    '    tick();',
    '  }',
    '}',
  ]),

  /** while(true) with a break in reach: bounded, so silent. */
  boundedRetry: fileDiff('src/poller-bounded.ts', [
    'export function poll(): void {',
    '  while (true) {',
    '    if (done()) break;',
    '  }',
    '}',
  ]),

  /** A focus modifier in a test file. */
  focusedTest: fileDiff('src/feature.test.ts', [
    'describe.only("feature", () => {',
    '  it("works", () => { expect(1).toBe(1); });',
    '});',
  ]),

  /** A skip modifier — the other half of the same rule. */
  skippedTest: fileDiff('src/feature.spec.ts', [
    'it.skip("works", () => { expect(1).toBe(1); });',
  ]),

  /** An unmocked clock in a test file. */
  unmockedClock: fileDiff('src/clock.test.ts', [
    'it("stamps", () => {',
    '  const at = Date.now();',
    '  expect(at).toBeGreaterThan(0);',
    '});',
  ]),

  /** The same clock, with fake timers in context: must not fire. */
  mockedClock: fileDiff('src/clock-mocked.test.ts', [
    'vi.useFakeTimers();',
    'it("stamps", () => {',
    '  const at = Date.now();',
    '  expect(at).toBeGreaterThan(0);',
    '});',
  ]),

  /** Unmocked randomness in a test file. */
  unmockedRandom: fileDiff('src/random.test.ts', [
    'it("picks", () => {',
    '  const pick = Math.random();',
    '  expect(pick).toBeLessThan(1);',
    '});',
  ]),

  /** A non-test file carrying the same patterns: the test rules must ignore it. */
  nonTestLookalike: fileDiff('src/random.ts', [
    'export const pick = (): number => Math.random();',
    'export const at = (): number => Date.now();',
  ]),

  /** Several rules at once, so an aggregate cannot hide one behind another. */
  multiRule: [
    fileDiff('src/handler.ts', [
      'try { work(); } catch (err) {}',
      'console.log("noise");',
    ]),
    fileDiff('src/feature.test.ts', [
      'describe.only("feature", () => {',
      '  console.log(Date.now());',
      '});',
    ]),
    fileDiff('src/big.ts', repeat('const value = 1;', 401)),
  ].join(''),

  /** A rename-only hunk header with no additions at all. */
  headerOnly: [
    'diff --git a/src/moved.ts b/src/relocated.ts',
    'similarity index 100%',
    'rename from src/moved.ts',
    'rename to src/relocated.ts',
    '',
  ].join('\n'),
});

/** Stable iteration order for the golden capture and the comparison. */
export const CORPUS_KEYS: readonly string[] = Object.freeze(Object.keys(DIFF_CORPUS).sort());
