/**
 * Catalog-registration gating lint (DR-33 / T-45).
 *
 * DR-30 — the two authorities here cannot observe each other. The population
 * comes from `git ls-files` over `skills-src/`; the discriminant that decides
 * whether a source is gated reads the catalog path and the Constraints step,
 * which is independent of the registration vocabulary the assertions check.
 * Task 079 replaced a hand-transcribed nine-file list scanned against a
 * 106-file tree — a denominator that could not notice the files it omitted.
 * @oracle-sources: git ls-files over skills-src/, the catalog-path + Constraints-step discriminant read from each source
 *
 * DR-31/T-43 retired the `invariants.devCatalog` boolean in favor of
 * `invariants.catalogs` registration as the ONE AND ONLY opt-in (see
 * `src/architecture/catalog-sources.ts`). Content sources that gate their
 * design-time (`/ideate`, `/refactor`, `/debug`) or evaluation-time
 * (`/shepherd`) Constraints step on the retired flag were re-pointed at
 * catalog registration.
 *
 * This lint pins two invariants over the source-of-truth `content/`
 * tree (not the rendered `skills/<runtime>/` variants, which vary by
 * runtime placeholder substitution and are regenerated by
 * `build:skills` from these same sources):
 *
 *   1. NO source anywhere under `skills-src/` mentions the retired `devCatalog`
 *      key (case-insensitive) — a reader must never be instructed to set a flag
 *      that no longer exists.
 *   2. Each source that gates a Constraints step on the catalog still expresses
 *      that gate, re-pointed at catalog *registration* (`invariants.catalogs` /
 *      "catalog is registered" / "catalog-registration").
 *
 * ── Populations are DERIVED, not transcribed (DR-8, task 079) ───────────────
 * Both invariants used to range over a hand-written nine-entry array against a
 * tree of 105 tracked markdown sources. That is the defect this programme
 * exists to close, in both directions:
 *
 *   • Invariant 1's claim is about the TREE, so scoping it to nine files meant a
 *     `devCatalog` planted in any of the other ninety-six was invisible. It now
 *     sweeps every tracked source.
 *   • Invariant 2's population is a PROPERTY — a source that anchors a
 *     Constraints step to the dev-invariants catalog — so it is derived from
 *     two independent signals: a reference to the catalog path, and a
 *     Constraints step. Neither is the registration vocabulary the invariant
 *     asserts, so this is not a comparison with itself.
 *
 * The transcribed list was already one file stale in the other direction:
 * `review/SKILL.md` expresses the gate and was never in it.
 */

import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const SKILLS_SRC = join(process.cwd(), 'content');

const CATALOG_REGISTRATION_RE =
  /invariants\.catalogs|catalog[- ]registration|catalog is registered|no catalog is registered/i;

/** The dev-invariants catalog a gated Constraints step anchors to. */
const CATALOG_PATH_RE = /\.exarchos\/invariants\.md/;

/** A Constraints step — the surface the catalog gate applies to. */
const CONSTRAINTS_STEP_RE = /\bConstraints\b/;

/**
 * Every markdown source the repository tracks under `skills-src/`.
 *
 * `git ls-files` is the second authority: it knows nothing about which files
 * this lint considers interesting, so it cannot inherit the lint's blind spot.
 * Throws rather than returning `[]` — an empty corpus would make both sweeps
 * below vacuously green.
 */
function trackedSkillSources(): string[] {
  const stdout = execFileSync('git', ['ls-files', '-z', '--', '*.md'], {
    cwd: SKILLS_SRC,
    encoding: 'utf-8',
    maxBuffer: 32 * 1024 * 1024,
  });
  const files = stdout.split('\0').filter((line) => line.length > 0).sort();
  if (files.length === 0) {
    throw new Error(
      `no markdown source tracked under ${SKILLS_SRC} — the corpus is empty, so ` +
        'every sweep over it would pass for the wrong reason',
    );
  }
  return files;
}

const read = (file: string): string => readFileSync(join(SKILLS_SRC, file), 'utf8');

/** Sources that anchor a Constraints step to the dev-invariants catalog. */
function catalogGatedSources(files: readonly string[]): string[] {
  return files.filter((file) => {
    const content = read(file);
    return CATALOG_PATH_RE.test(content) && CONSTRAINTS_STEP_RE.test(content);
  });
}

describe('catalog-registration gating lint (DR-33)', () => {
  it('SkillsSrc_NoSourceAnywhereMentionsTheRetiredDevCatalogFlag', () => {
    // WHOLE TREE. The claim is about the corpus, so the sweep is too: a
    // `devCatalog` instruction planted in any source outside the superseded
    // nine-file list used to be invisible to this lint.
    const files = trackedSkillSources();
    expect(files.length).toBeGreaterThan(0);

    const offenders = files.filter((file) => /devCatalog/i.test(read(file)));
    expect(
      offenders,
      'these skills-src sources instruct the reader to set `invariants.devCatalog`, ' +
        'a flag DR-31/T-43 retired — re-point them at `invariants.catalogs` registration',
    ).toEqual([]);
  });

  it('SkillsSrc_EveryCatalogGatedSource_ExpressesTheRegistrationGate', () => {
    const files = trackedSkillSources();
    const gated = catalogGatedSources(files);

    // NON-EMPTY DENOMINATOR: a discriminant that selected nothing would make the
    // assertion below vacuous.
    expect(
      gated.length,
      'no skills-src source was identified as catalog-gated — the discriminant ' +
        'stopped matching, so this lint is asserting nothing',
    ).toBeGreaterThan(0);
    // …and it is a real subset, not the whole tree by accident.
    expect(gated.length).toBeLessThan(files.length);

    const missing = gated.filter((file) => !CATALOG_REGISTRATION_RE.test(read(file)));
    expect(
      missing,
      'these sources gate a Constraints step on the dev-invariants catalog but ' +
        'never say the gate is catalog REGISTRATION — a reader is left without ' +
        'the opt-in condition',
    ).toEqual([]);
  });

  it('SkillsSrcGating_DiscriminantIsIndependentOfTheAssertedVocabulary', () => {
    // The old test asserted a transcribed list contained what the list declared.
    // This one has to avoid the same shape: if the discriminant that selects the
    // population were the registration vocabulary itself, the assertion above
    // could never fail.
    //
    // It cannot: the discriminant is (catalog path) AND (Constraints step),
    // neither of which is CATALOG_REGISTRATION_RE. Demonstrated on synthetic
    // text so the claim does not depend on the live corpus.
    const gatedButSilent = 'Load `.exarchos/invariants.md` and emit Constraints before the brief.';
    expect(CATALOG_PATH_RE.test(gatedButSilent) && CONSTRAINTS_STEP_RE.test(gatedButSilent)).toBe(
      true,
    );
    expect(
      CATALOG_REGISTRATION_RE.test(gatedButSilent),
      'a source can be selected by the discriminant and still FAIL the assertion — ' +
        'which is what makes the assertion capable of failing at all',
    ).toBe(false);
  });

  it('SkillsSrcGating_PopulationTracksTheTree_NotATranscribedList', () => {
    // The derived population is not the superseded nine-entry array. It picks up
    // `review/SKILL.md`-class sources the moment they gate on the catalog, and
    // the whole-tree devCatalog sweep covers every source either way.
    const files = trackedSkillSources();
    const gated = catalogGatedSources(files);

    // The corpus is far larger than the population the old list named, which is
    // exactly why scoping invariant 1 to that list was a hole.
    expect(files.length).toBeGreaterThan(gated.length * 2);

    // Every selected source is a real, readable file resolved from the tree.
    for (const file of gated) {
      expect(file.endsWith('.md')).toBe(true);
      expect(read(file).length).toBeGreaterThan(0);
    }
  });
});
