// Generated by `exarchos build:hooks` (#1485). Do NOT hand-edit.
//
// Observe-only opencode lifecycle plugin. opencode plugins react to events and
// CANNOT inject context at session start, so the Exarchos *binding* directive is
// carried by AGENTS.md (the universal always-loaded floor), not this plugin.
// This plugin's sole job is the start-half of the observe-loop: emit
// `session.started` telemetry via the runtime-agnostic `exarchos session-start`
// CLI. The session-end equivalent is deferred — opencode's `session.idle` is not
// a clean end signal (it can fire repeatedly) and session-end's transcript
// parser is Claude-specific (cross-runtime provenance is a tracked follow-up).
export const ExarchosLifecycle = async ({ $ }) => {
  return {
    event: async ({ event }) => {
      if (event.type === 'session.created') {
        await $`exarchos session-start`.quiet().nothrow();
      }
    },
  };
};
