/**
 * Drive the prose exodus: generate the manifest, copy to the destination,
 * reconcile.
 *
 * Three subcommands, deliberately separate so the destructive one is never a
 * side effect of the safe ones:
 *
 *   generate  — read the reference census, take every subtree with ZERO live
 *               referrers, and write `tools/audit/prose-manifest.json`.
 *   transfer  — copy every manifest entry into a checkout of the destination
 *               repository. Idempotent; writes nothing outside the key.
 *   reconcile — recompute every digest at the destination and report.
 *
 * Deletion is NOT a subcommand here. It is `git rm` performed by a human or a
 * task that has read a passing reconciliation, because the whole design intent
 * is that removal is a separate decision from preservation.
 */
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  buildManifest,
  formatReconcile,
  isRetained,
  reconcile,
  type ProseManifest,
} from './prose-manifest.js';

const REPO_ROOT = process.cwd();
const MANIFEST_PATH = path.join(REPO_ROOT, 'tools/audit/prose-manifest.json');

/**
 * Every tracked path under `docs/` that is NOT retained.
 *
 * Enumerated from git rather than from a list of subtree names, so a directory
 * added under `docs/` is relocated by default and has to be argued INTO
 * {@link RETAINED} to stay. The old rule ran the other way and let anything new
 * accumulate silently.
 */
function relocatablePaths(): string[] {
  const tracked = execFileSync('git', ['-C', REPO_ROOT, 'ls-files', '-z', '--', 'docs'], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
    .split('\0')
    .filter((rel) => rel.length > 0);

  const relocatable = tracked.filter((rel) => !isRetained(rel)).sort();
  if (tracked.length === 0) {
    throw new Error(
      'git reports no tracked file under docs/ — a manifest over nothing reconciles clean ' +
        'against a destination that received nothing',
    );
  }
  return relocatable;
}

function loadManifest(): ProseManifest {
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as ProseManifest;
}

function generate(capturedAt: string): void {
  const paths = relocatablePaths();
  const fresh = buildManifest(REPO_ROOT, paths, capturedAt);

  // MERGED, not replaced. The manifest is the standing record of everything
  // ever relocated, and it is generated by enumerating the tree — so a file
  // moved in an earlier pass is no longer there to be enumerated. Replacing
  // would drop it from the record while it still sits at the destination,
  // leaving preservation unprovable for exactly the files that were preserved
  // first.
  const prior: ProseManifest | undefined = existsSync(MANIFEST_PATH) ? loadManifest() : undefined;
  const byDestination = new Map((prior?.entries ?? []).map((e) => [e.destination, e]));
  for (const entry of fresh.entries) byDestination.set(entry.destination, entry);

  const entries = [...byDestination.values()].sort((a, b) => a.source.localeCompare(b.source));
  const manifest: ProseManifest = {
    ...fresh,
    subtrees: [...new Set(entries.map((e) => e.source.split('/').slice(0, 2).join('/')))].sort(),
    counts: { files: entries.length, bytes: entries.reduce((n, e) => n + e.bytes, 0) },
    entries,
  };

  // The manifest is a RECORD of what was preserved, and it is generated by
  // enumerating the tree — so once the files are deleted, a regeneration
  // enumerates nothing and would replace the record with an empty one. It would
  // then reconcile clean against any destination, including one that lost
  // everything.
  //
  // A record whose only copy is destroyed by re-running the tool that wrote it
  // is not a record. Shrinking is refused; a deliberate reduction goes through
  // `--allow-shrink` so it is visible in the shell history and the diff.
  if (existsSync(MANIFEST_PATH)) {
    const prior = loadManifest();
    if (manifest.entries.length < prior.entries.length && !process.argv.includes('--allow-shrink')) {
      throw new Error(
        `refusing to shrink the manifest from ${prior.entries.length} to ${manifest.entries.length} ` +
          'entries. Regeneration enumerates TRACKED files, so running this after the deletion ' +
          'produces an empty record that reconciles clean against nothing. Generate before ' +
          'deleting, or pass --allow-shrink if the reduction is intended.',
      );
    }
  }

  writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  console.log(
    `[prose-exodus] manifest: ${manifest.counts.files} file(s), ` +
      `${manifest.counts.bytes} bytes, across ${manifest.subtrees.length} subtree(s)`,
  );
  for (const subtree of manifest.subtrees) console.log(`  ${subtree}`);
}

function transfer(destinationRoot: string): void {
  const manifest = loadManifest();
  let copied = 0;
  let alreadyGone = 0;

  for (const entry of manifest.entries) {
    const source = path.join(REPO_ROOT, entry.source);
    // The manifest is a standing record across passes, so it holds entries
    // whose source was removed in an EARLIER one. Those are already at the
    // destination — `reconcile` is what proves it — and re-copying is not
    // merely unnecessary, it is impossible.
    if (!existsSync(source)) {
      alreadyGone += 1;
      continue;
    }
    const dest = path.join(destinationRoot, entry.destination);
    mkdirSync(path.dirname(dest), { recursive: true });
    copyFileSync(source, dest);
    copied += 1;
  }

  console.log(
    `[prose-exodus] copied ${copied} file(s) to ${destinationRoot}` +
      (alreadyGone > 0 ? `; ${alreadyGone} already relocated in an earlier pass` : ''),
  );
}

function runReconcile(destinationRoot: string): void {
  const result = reconcile(loadManifest(), destinationRoot);
  console.log(`[prose-exodus] ${formatReconcile(result)}`);
  if (!result.ok) process.exit(1);
}

const [command, arg] = process.argv.slice(2);
switch (command) {
  case 'generate':
    // The timestamp is an argument rather than `new Date()` so a regeneration
    // that changes nothing else produces no diff.
    generate(arg ?? new Date().toISOString().slice(0, 10));
    break;
  case 'transfer':
    if (arg === undefined) throw new Error('transfer requires a destination checkout path');
    transfer(arg);
    break;
  case 'reconcile':
    if (arg === undefined) throw new Error('reconcile requires a destination checkout path');
    runReconcile(arg);
    break;
  default:
    console.error('usage: prose-exodus-cli <generate [date] | transfer <dest> | reconcile <dest>>');
    process.exit(2);
}
