// ─── runtimes/copilot.yaml supportedCapabilities + spawn-call tests ────────
//
// Pins the corrections from Task 7e:
//
//   1. SPAWN_AGENT_CALL must use the LOCAL Copilot CLI subagent primitive
//      (`task --agent <name>`), not `/delegate` (which ships work to the
//      cloud Copilot Coding Agent and opens a PR — wrong shape for our
//      worktree fan-out). See discovery §3 (Copilot row) + §4 Class 2.
//
//   2. The spawn call must reference an agent NAME — the bare-name form
//      derived from `copilotAdapter.agentFilePath('implementer')` —
//      because Copilot's local custom-agent loader keys off the filename
//      (`<name>.agent.md`), not the full path.
//
//   3. `supportedCapabilities` must be a YAML mapping that mirrors
//      `copilotAdapter.supportLevels`: 5 native + 2 advisory entries
//      (the 3 unsupported capabilities are absent by contract).
//
//   4. The previous YAML's "we knowingly picked the wrong primitive"
//      justification block must be removed — the comment was load-bearing
//      documentation for the wrong choice and is misleading once corrected.
//
// Implements: Task 7e of docs/plans/2026-04-25-delegation-runtime-parity.md.
// ────────────────────────────────────────────────────────────────────────────

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as yamlParse } from 'yaml';
import { CopilotAdapter } from '../agents/adapters/copilot.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// `runtimes/copilot.yaml` lives at the repo root, four levels up from this
// test file (servers/exarchos-mcp/src/runtimes/copilot.test.ts).
const COPILOT_YAML_PATH = resolve(
  __dirname,
  '..',
  '..',
  '..',
  '..',
  'runtimes',
  'copilot.yaml',
);

function loadCopilotYamlText(): string {
  return readFileSync(COPILOT_YAML_PATH, 'utf8');
}

function loadCopilotYaml(): Record<string, unknown> {
  const parsed = yamlParse(loadCopilotYamlText());
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(
      `Expected ${COPILOT_YAML_PATH} to parse to an object, got ${
        parsed === null ? 'null' : typeof parsed
      }`,
    );
  }
  return parsed as Record<string, unknown>;
}

/** Derive the bare agent name from the adapter's path, e.g. "implementer". */
function bareAgentName(adapterPath: string): string {
  // adapterPath looks like ".github/agents/<name>.agent.md".
  const filename = adapterPath.split('/').pop() ?? '';
  return filename.replace(/\.agent\.md$/, '');
}

describe('runtimes/copilot.yaml — local task --agent primitive', () => {
  it('CopilotYaml_SpawnAgentCall_UsesLocalTaskAgentNotDelegate', () => {
    const data = loadCopilotYaml();
    const placeholders = data.placeholders as Record<string, unknown>;
    const spawn = placeholders?.SPAWN_AGENT_CALL;

    expect(typeof spawn).toBe('string');
    const spawnStr = spawn as string;

    // Must invoke the local custom-agent path. Copilot CLI exposes this
    // via the `task` tool with a `--agent <name>` programmatic flag.
    // Reference: https://docs.github.com/en/copilot/how-tos/copilot-cli/customize-copilot/create-custom-agents-for-cli
    expect(spawnStr).toContain('task --agent');

    // Must NOT use `/delegate`. That primitive ships work to the cloud
    // Copilot Coding Agent and opens a PR — async, remote, wrong shape
    // for Exarchos's in-session worktree fan-out. (Discovery §3 row,
    // Class 2 leak.)
    expect(spawnStr).not.toContain('/delegate');
  });

  it('CopilotYaml_SpawnAgentCall_ReferencesGeneratedAgentName', () => {
    const data = loadCopilotYaml();
    const placeholders = data.placeholders as Record<string, unknown>;
    const spawn = placeholders?.SPAWN_AGENT_CALL as string;

    // The agent identifier passed to `--agent` must be the bare name
    // generated by the Copilot adapter (not the full file path).
    // copilotAdapter.agentFilePath('implementer') → ".github/agents/implementer.agent.md"
    // bare name → "implementer".
    const adapter = new CopilotAdapter();
    const expectedName = bareAgentName(adapter.agentFilePath('implementer'));
    expect(expectedName).toBe('implementer');

    // The placeholder template uses {{agent}} / a literal name slot — the
    // contract is that the bare name "implementer" appears as the natural
    // referent. Either a literal substring or the templated form
    // `--agent implementer` must be present.
    const referencesBareName =
      spawn.includes(`--agent ${expectedName}`) ||
      // Allow templated form so the renderer can substitute per-spec.
      /--agent\s+\{\{\s*\w+\s*\}\}/.test(spawn);
    expect(referencesBareName).toBe(true);
  });

  it('CopilotYaml_SupportedCapabilities_FiveNativeTwoAdvisory', () => {
    const data = loadCopilotYaml();
    const supported = data.supportedCapabilities;

    // Must be a YAML mapping (object), not a list/array. The prose
    // renderer (Tasks 8/9) needs per-capability support-level strings
    // to gate `<!-- requires:* -->` vs `<!-- requires:native:* -->`.
    expect(supported).toBeDefined();
    expect(supported).not.toBeNull();
    expect(Array.isArray(supported)).toBe(false);
    expect(typeof supported).toBe('object');

    const map = supported as Record<string, unknown>;

    // Per Task 4f's COPILOT_SUPPORT_LEVELS:
    //   native (5):    fs:read, fs:write, shell:exec, subagent:spawn, mcp:exarchos
    //   advisory (2):  isolation:worktree, session:resume
    //   unsupported (3, omitted): subagent:completion-signal,
    //                             subagent:start-signal, team:agent-teams
    const expectedNative = [
      'fs:read',
      'fs:write',
      'shell:exec',
      'subagent:spawn',
      'mcp:exarchos',
    ];
    const expectedAdvisory = ['isolation:worktree', 'session:resume'];

    for (const key of expectedNative) {
      expect(map, `missing native capability '${key}'`).toHaveProperty(key);
      expect(map[key], `'${key}' should be 'native'`).toBe('native');
    }
    for (const key of expectedAdvisory) {
      expect(map, `missing advisory capability '${key}'`).toHaveProperty(key);
      expect(map[key], `'${key}' should be 'advisory'`).toBe('advisory');
    }

    // The 3 unsupported capabilities are absent from the mapping by
    // contract. No additional keys beyond the 5 + 2 above.
    expect(Object.keys(map).sort()).toEqual(
      [...expectedNative, ...expectedAdvisory].sort(),
    );
  });

  it('CopilotYaml_AdapterAlignment_MatchesSupportLevels', () => {
    const data = loadCopilotYaml();
    const supported = data.supportedCapabilities as Record<string, unknown>;
    const adapter = new CopilotAdapter();

    for (const [cap, level] of Object.entries(adapter.supportLevels)) {
      if (level === 'unsupported') {
        // Unsupported capabilities are absent from the YAML by contract.
        expect(
          Object.prototype.hasOwnProperty.call(supported, cap),
          `unsupported capability '${cap}' must NOT appear in supportedCapabilities`,
        ).toBe(false);
        continue;
      }
      expect(
        supported[cap],
        `copilot.yaml.supportedCapabilities['${cap}'] should match adapter level '${level}'`,
      ).toBe(level);
    }
  });

  it('CopilotYaml_StaleJustificationComment_Removed', () => {
    const text = loadCopilotYamlText();

    // The previous YAML had a comment block justifying the wrong-primitive
    // pick over the local `task` tool. Once we switch to `task --agent`,
    // that comment is misleading and must be removed entirely. Match on
    // the load-bearing phrases (case-insensitive) — small wording drift
    // shouldn't false-pass.
    const forbiddenPhrases = [
      /async\s+cloud\s+worker/i,
      /we\s+pick\s+\/delegate/i,
      /may\s+be\s+used\s+by\s+a\s+future\s+variant/i,
      /knowingly\s+picked\s+the\s+wrong\s+primitive/i,
      /Why we pick \/delegate over the `task` tool/i,
    ];
    for (const pattern of forbiddenPhrases) {
      expect(
        text,
        `stale justification phrase ${pattern} must not appear in copilot.yaml`,
      ).not.toMatch(pattern);
    }
  });
});
