/**
 * The context-economy checker. It reads a unified diff for patterns that cost LLM context: oversized source files, wide diffs, and large generated files.
 * It reads only the diff and does not access the file system.
 */

/** Severity levels for findings. */
export type Severity = 'HIGH' | 'MEDIUM' | 'LOW';

/** A single context-economy finding. */
export interface ContextEconomyFinding {
  readonly severity: Severity;
  readonly message: string;
}

/** Result of running the context-economy checks. */
export interface ContextEconomyResult {
  /** Whether all checks passed (no findings). */
  readonly pass: boolean;
  /** Total number of checks that were executed. */
  readonly checksRun: number;
  /** Number of checks that passed without findings. */
  readonly checksPassed: number;
  /** Individual findings, empty when pass === true. */
  readonly findings: readonly ContextEconomyFinding[];
}

interface ParsedFile {
  readonly name: string;
  readonly addedLines: readonly string[];
}

/**
 * Parse a unified diff into per-file added-line arrays.
 *
 * Only lines starting with `+` (excluding `+++` header lines) are counted
 * as added lines.
 */
function parseDiff(diff: string): ParsedFile[] {
  const files: ParsedFile[] = [];
  let currentName = '';
  let currentAdded: string[] = [];

  for (const line of diff.split('\n')) {
    const headerMatch = line.match(/^diff --git a\/(.+?) b\//);
    if (headerMatch) {
      if (currentName) {
        files.push({ name: currentName, addedLines: currentAdded });
      }
      currentName = headerMatch[1] ?? '';
      currentAdded = [];
      continue;
    }

    if (line.startsWith('+++ ')) {
      continue;
    }

    if (line.startsWith('+')) {
      currentAdded.push(line.slice(1));
    }
  }

  if (currentName) {
    files.push({ name: currentName, addedLines: currentAdded });
  }

  return files;
}

/** Check if a file is a TypeScript or JavaScript source file. */
function isSourceFile(name: string): boolean {
  return name.endsWith('.ts') || name.endsWith('.js');
}

const SOURCE_FILE_LENGTH_THRESHOLD = 400;
const DIFF_BREADTH_THRESHOLD = 30;
const GENERATED_FILE_THRESHOLD = 1000;

const GENERATED_MARKERS_RE =
  /@generated|AUTO-GENERATED|eslint-disable|auto[- ]?generated|do not edit|generated by|this file is generated|machine generated/i;

/**
 * Check 1: Source file length (>400 added lines for .ts/.js files).
 */
function checkSourceFileLength(files: readonly ParsedFile[]): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  const findings: ContextEconomyFinding[] = [];

  for (const file of files) {
    if (!isSourceFile(file.name)) continue;
    if (file.addedLines.length > SOURCE_FILE_LENGTH_THRESHOLD) {
      findings.push({
        severity: 'MEDIUM',
        message: `\`${file.name}\` — Source file exceeds 400 lines (${file.addedLines.length} added lines)`,
      });
    }
  }

  return { findings, passed: findings.length === 0 };
}

/**
 * Check 2: function and method length. It needs the files for brace counting, so it always passes in diff-only mode.
 * `checkContextEconomy` does not call it.
 */
function checkFunctionLength(): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  return { findings: [], passed: true };
}

/**
 * Check 3: Diff breadth (>30 files changed).
 */
function checkDiffBreadth(files: readonly ParsedFile[]): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  const findings: ContextEconomyFinding[] = [];

  if (files.length > DIFF_BREADTH_THRESHOLD) {
    findings.push({
      severity: 'MEDIUM',
      message: `Diff breadth: ${files.length} files changed (threshold: ${DIFF_BREADTH_THRESHOLD})`,
    });
  }

  return { findings, passed: findings.length === 0 };
}

/**
 * Check 4: Large generated files (>1000 added lines with markers).
 *
 * In diff-only mode:
 * - If a generated marker is detected AND there are added lines -> finding (LOW)
 * - If >1000 added lines without marker -> "possible generated file" (LOW)
 */
function checkLargeGeneratedFiles(files: readonly ParsedFile[]): {
  findings: ContextEconomyFinding[];
  passed: boolean;
} {
  const findings: ContextEconomyFinding[] = [];

  for (const file of files) {
    const hasMarker = file.addedLines.some((line) =>
      GENERATED_MARKERS_RE.test(line),
    );
    const addedCount = file.addedLines.length;

    if (hasMarker && addedCount > 0) {
      findings.push({
        severity: 'LOW',
        message: `\`${file.name}\` — Generated file detected in diff (${addedCount} added lines)`,
      });
    } else if (addedCount > GENERATED_FILE_THRESHOLD) {
      findings.push({
        severity: 'LOW',
        message: `\`${file.name}\` — ${addedCount} added lines (possible generated file, threshold: ${GENERATED_FILE_THRESHOLD})`,
      });
    }
  }

  return { findings, passed: findings.length === 0 };
}

/**
 * Runs the context-economy checks on a unified diff string.
 * The function-length check needs file system access, so it does not run and is not counted in `checksRun` or `checksPassed`.
 *
 * @param diff - A unified diff string (as produced by `git diff`).
 * @returns The aggregated check result.
 */
export function checkContextEconomy(diff: string): ContextEconomyResult {
  if (!diff.trim()) {
    return { pass: true, checksRun: 0, checksPassed: 0, findings: [] };
  }

  const files = parseDiff(diff);

  const checks = [
    checkSourceFileLength(files),
    checkDiffBreadth(files),
    checkLargeGeneratedFiles(files),
  ];

  const allFindings = checks.flatMap((c) => c.findings);
  const passed = checks.filter((c) => c.passed).length;

  return {
    pass: allFindings.length === 0,
    checksRun: checks.length,
    checksPassed: passed,
    findings: allFindings,
  };
}
