// ─── `exarchos <harness>` launcher verb — schema + dry-run + non-dry-run seam ─
//
// A CLI-only process-supervisor verb (the stdio MCP surface cannot own a
// child's lifecycle), so this module owns:
//
//   - the Zod verb schema (`<harness>` enum + `--feature` + `--dry-run`),
//   - `runLauncherVerb` — validates input, resolves the harness via the shared
//     `resolveHarness` (unknown → structured error carrying `validTargets`),
//     and on `--dry-run` derives the worktree path via the SAME
//     `topology.deriveWorktreePath` creation will use (Task 005) and returns
//     the event plan WITHOUT creating a worktree or spawning a process,
//   - `renderDryRunPlan` — the human-readable dry-run output (deliberately free
//     of any space / enforcement / confinement claim — an explicit non-goal of
//     this feature).
//
// The non-dry-run path is a clearly-marked, typed seam ({@link LifecycleRunner}):
// until Task 010 provides `./lifecycle-core#runLifecycle`, a non-dry-run launch
// returns a structured `NOT_WIRED` result. Task 010 fills the seam by injecting
// a runner — no reshaping of the verb required.
//
// Implements:
//   - DR-1: the `exarchos <harness>` launcher verb — schema-constrained enum,
//     Aspire-style, `--dry-run`-capable; unknown harness → `validTargets`.
// ────────────────────────────────────────────────────────────────────────────

import { z } from 'zod';
import {
  TIER1_HARNESSES,
  resolveHarness,
  type HarnessTarget,
  type RuntimeId,
} from './harness-registry.js';
import { deriveWorktreePath } from './topology.js';
import type { ToolResult } from '../format.js';

// ============================================================
// Event plan (what a real launch WOULD emit)
// ============================================================

/**
 * The ordered event plan a real (non-dry-run) launch WOULD emit, previewed by
 * `--dry-run`. Mirrors the DR-2 lifecycle exactly:
 *
 *   1. `worktree.reserved`          — ownership (before `git worktree add`)
 *   2. `worktree.create.requested`  — INV-13 creation intent
 *   3. `worktree.create.executed`   — INV-13 creation terminal (shared stem)
 *   4. `launch.executing_started`   — liveness start
 *   5. `launch.executed`            — liveness terminal (child exited)
 *
 * This is the single source of truth for the dry-run preview; the concrete
 * emissions are owned by Tasks 005 (create pair) and 006 (launch pair).
 */
export const LAUNCH_EVENT_PLAN = [
  'worktree.reserved',
  'worktree.create.requested',
  'worktree.create.executed',
  'launch.executing_started',
  'launch.executed',
] as const;

/** A single event type in the {@link LAUNCH_EVENT_PLAN}. */
export type LaunchEventType = (typeof LAUNCH_EVENT_PLAN)[number];

// ============================================================
// Verb schema (DR-1)
// ============================================================

/**
 * Zod schema for the `exarchos <harness>` verb.
 *
 * - `harness` is constrained to the five Tier-1 harness enum members
 *   ({@link TIER1_HARNESSES}) — the schema itself rejects any non-enum value.
 * - `feature` is an optional feature id the launch worktree is associated with.
 * - `dryRun` toggles the preview-only path (default `false`).
 *
 * The enum is sourced from {@link TIER1_HARNESSES} so the schema constraint and
 * the `resolveHarness` `validTargets` error can never drift apart.
 */
export const LauncherVerbSchema = z.object({
  harness: z.enum(TIER1_HARNESSES),
  feature: z.string().min(1).optional(),
  dryRun: z.boolean().optional().default(false),
});

/** Parsed, validated launcher verb input. */
export type LauncherVerbInput = z.infer<typeof LauncherVerbSchema>;

// ============================================================
// Worktree-id derivation (preview stand-in)
// ============================================================

/**
 * Derive the single-segment worktree id previewed by `--dry-run`.
 *
 * This is a **preview stand-in**: the authoritative id (carrying the
 * `operationId`) is generated by the creation path (Task 005). It is factored
 * out here so the dry-run path derives a *valid single segment*
 * ({@link deriveWorktreePath} rejects separators / traversal tokens) and so
 * Task 005 can reuse or supersede it without reshaping the verb.
 *
 * The feature id (if any) is sanitized to a safe segment fragment — any
 * character outside `[A-Za-z0-9._-]` collapses to `-` — so a feature like
 * `feat/x` cannot push the derived path deeper than one level.
 */
export function deriveLaunchWorktreeId(harness: HarnessTarget, feature?: string): string {
  const base = `exarchos-${harness}`;
  if (feature === undefined || feature.length === 0) return base;
  const safeFeature = feature.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
  return safeFeature.length > 0 ? `${base}-${safeFeature}` : base;
}

// ============================================================
// Dry-run plan
// ============================================================

/**
 * Structured dry-run preview: the derived worktree path + the event plan a
 * real launch would emit. Carries `base` and `worktreeId` so a consumer can
 * independently re-derive the path via {@link deriveWorktreePath} and confirm
 * the verb used the SAME guard as creation (not a re-implementation).
 */
export interface DryRunPlan {
  readonly harness: HarnessTarget;
  readonly runtimeId: RuntimeId;
  readonly feature: string | null;
  /** Base worktree the launcher worktree is a sibling of. */
  readonly base: string;
  /** Single-segment id the derived path is built from. */
  readonly worktreeId: string;
  /** Derived sibling worktree path (via {@link deriveWorktreePath}). */
  readonly worktreePath: string;
  /** The ordered events a real launch would emit (none emitted in dry-run). */
  readonly eventPlan: readonly LaunchEventType[];
}

// ============================================================
// Non-dry-run lifecycle seam (Task 010 fills this)
// ============================================================

/**
 * The resolved launch context handed to the lifecycle runner on the non-dry-run
 * path. Task 010's `./lifecycle-core#runLifecycle` consumes this to create the
 * worktree, place the child, exec the harness, and tear down.
 */
export interface ResolvedLaunch {
  readonly harness: HarnessTarget;
  readonly runtimeId: RuntimeId;
  readonly feature: string | null;
  readonly base: string;
  readonly worktreeId: string;
  readonly worktreePath: string;
}

/**
 * The non-dry-run lifecycle entrypoint seam.
 *
 * Task 010 provides the real implementation
 * (`./lifecycle-core#runLifecycle`) and injects it via
 * {@link LauncherVerbDeps.lifecycle}. Until then a non-dry-run launch returns a
 * structured `NOT_WIRED` result. Typed here so Task 010 fills the seam WITHOUT
 * reshaping the verb.
 */
export type LifecycleRunner = (launch: ResolvedLaunch) => Promise<ToolResult>;

/** Injectable dependencies for {@link runLauncherVerb}. */
export interface LauncherVerbDeps {
  /**
   * Base worktree path off which the launcher worktree is derived as a sibling.
   * Defaults to `process.cwd()`. Injected in tests for determinism.
   */
  readonly base?: string;
  /**
   * The non-dry-run lifecycle runner (Task 010). Absent → non-dry-run returns
   * `NOT_WIRED`. Never invoked on the `--dry-run` path.
   */
  readonly lifecycle?: LifecycleRunner;
}

// ============================================================
// Verb core
// ============================================================

/** Build the INVALID_INPUT ToolResult for a Zod validation failure. */
function invalidInput(message: string): ToolResult {
  return { success: false, error: { code: 'INVALID_INPUT', message } };
}

/**
 * Run the `exarchos <harness>` verb.
 *
 * Flow:
 *   1. Resolve the harness via {@link resolveHarness} — an unknown value
 *      returns a structured `INVALID_INPUT` error carrying `validTargets` (the
 *      five enum members), never a throw.
 *   2. Validate the remaining input (`feature`, `dryRun`) via
 *      {@link LauncherVerbSchema}.
 *   3. `--dry-run`: derive the worktree path via {@link deriveWorktreePath}
 *      (the SAME guard creation uses) and return the {@link DryRunPlan} — NO
 *      worktree created, NO process spawned.
 *   4. non-dry-run: delegate to the injected {@link LifecycleRunner} (Task 010)
 *      or, absent one, return a structured `NOT_WIRED` result.
 */
export async function runLauncherVerb(
  raw: unknown,
  deps: LauncherVerbDeps = {},
): Promise<ToolResult> {
  if (raw === null || typeof raw !== 'object') {
    return invalidInput('launcher verb input must be an object');
  }
  const rawInput = raw as Record<string, unknown>;

  // (1) Resolve harness FIRST so an unknown value yields the structured
  // `validTargets` error (independent of the schema's enum rejection).
  const harnessValue = rawInput.harness;
  const resolution = resolveHarness(
    typeof harnessValue === 'string' ? harnessValue : String(harnessValue),
  );
  if (!resolution.success) {
    return {
      success: false,
      error: {
        code: resolution.code,
        message: resolution.message,
        validTargets: resolution.validTargets,
      },
    };
  }

  // (2) Validate the full input through the schema (feature / dryRun shape).
  const parsed = LauncherVerbSchema.safeParse(rawInput);
  if (!parsed.success) {
    return invalidInput(
      parsed.error.issues
        .map((i) => `${i.path.length > 0 ? i.path.join('.') : '(root)'}: ${i.message}`)
        .join('; '),
    );
  }

  const { harness, feature, dryRun } = parsed.data;
  const base = deps.base ?? process.cwd();
  const worktreeId = deriveLaunchWorktreeId(harness, feature);

  // Derive the sibling worktree path via the SHARED pure guard — the same
  // function the creation task (005) calls before `git worktree add`. A bad id
  // (traversal / separator) surfaces as a structured error, not a throw.
  let worktreePath: string;
  try {
    worktreePath = deriveWorktreePath(base, worktreeId);
  } catch (err) {
    return invalidInput(
      `cannot derive launcher worktree path: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  // (3) Dry-run: preview only — no worktree, no spawn.
  if (dryRun) {
    const plan: DryRunPlan = {
      harness,
      runtimeId: resolution.runtimeId,
      feature: feature ?? null,
      base,
      worktreeId,
      worktreePath,
      eventPlan: LAUNCH_EVENT_PLAN,
    };
    return { success: true, data: plan };
  }

  // (4) Non-dry-run: delegate to the lifecycle runner (Task 010) or report the
  // seam is not yet wired. Kept typed so Task 010 fills it without reshaping.
  if (deps.lifecycle) {
    return deps.lifecycle({
      harness,
      runtimeId: resolution.runtimeId,
      feature: feature ?? null,
      base,
      worktreeId,
      worktreePath,
    });
  }
  return {
    success: false,
    error: {
      code: 'NOT_WIRED',
      message:
        'exarchos <harness>: non-dry-run lifecycle binding lands in task-010 (real verb→lifecycle spawn). Re-run with --dry-run to preview the derived worktree path + event plan.',
    },
  };
}

// ============================================================
// Dry-run rendering (human output — no enforcement claim)
// ============================================================

/**
 * Render a {@link DryRunPlan} as human-readable CLI output.
 *
 * The output is deliberately confined to lifecycle facts — the harness, its
 * runtime, the derived worktree path, and the ordered event plan. It makes NO
 * space / enforcement / confinement / sandbox / boundary claim, because
 * filesystem-write confinement is an explicit non-goal of this launcher (see
 * the spec's chokepoint table). `Verb_DryRun_NoEnforcementClaimInOutput`
 * pins that absence.
 */
export function renderDryRunPlan(plan: DryRunPlan): string {
  const lines: string[] = [];
  lines.push(`[dry-run] exarchos ${plan.harness} (runtime: ${plan.runtimeId})`);
  if (plan.feature) lines.push(`  feature:       ${plan.feature}`);
  lines.push(`  base:          ${plan.base}`);
  lines.push(`  worktree path: ${plan.worktreePath}`);
  lines.push('  event plan (would emit; none emitted in dry-run):');
  plan.eventPlan.forEach((event, index) => {
    lines.push(`    ${index + 1}. ${event}`);
  });
  lines.push('  (no worktree created, no process spawned)');
  return lines.join('\n');
}

// ============================================================
// Type guard for the dry-run result shape
// ============================================================

/**
 * Narrow a successful {@link ToolResult} whose `data` is a {@link DryRunPlan}.
 * Used by the CLI adapter to choose human rendering vs the JSON envelope.
 */
export function isDryRunPlan(data: unknown): data is DryRunPlan {
  if (data === null || typeof data !== 'object') return false;
  const d = data as Record<string, unknown>;
  return (
    typeof d.worktreePath === 'string' &&
    typeof d.worktreeId === 'string' &&
    Array.isArray(d.eventPlan)
  );
}
