/**
 * Catalog-registration gating lint (DR-33 / T-45).
 *
 * DR-31/T-43 retired the `invariants.devCatalog` boolean in favor of
 * `invariants.catalogs` registration as the ONE AND ONLY opt-in (see
 * `servers/exarchos-mcp/src/architecture/catalog-sources.ts`). Nine
 * skills-src sources still instructed the reader to gate the
 * design-time (`/ideate`, `/refactor`, `/debug`) or evaluation-time
 * (`/shepherd`) Constraints step on the retired `devCatalog` flag.
 *
 * This lint pins two invariants over the source-of-truth `skills-src/`
 * tree (not the rendered `skills/<runtime>/` variants, which vary by
 * runtime placeholder substitution and are regenerated by
 * `build:skills` from these same sources):
 *
 *   1. None of the nine affected files mention the retired `devCatalog`
 *      key (case-insensitive) — a reader must never be instructed to
 *      set a flag that no longer exists.
 *   2. Each of the nine files still expresses the gate, just re-pointed
 *      at catalog *registration* (`invariants.catalogs` / "catalog is
 *      registered" / "catalog-registration").
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const SKILLS_SRC = join(process.cwd(), 'skills-src');

const CATALOG_REGISTRATION_RE =
  /invariants\.catalogs|catalog[- ]registration|catalog is registered|no catalog is registered/i;

const AFFECTED_FILES: ReadonlyArray<{
  readonly id: string;
  readonly segments: readonly string[];
}> = [
  { id: 'debug/SKILL.md', segments: ['debug', 'SKILL.md'] },
  {
    id: 'debug/references/thorough-track.md',
    segments: ['debug', 'references', 'thorough-track.md'],
  },
  { id: 'ideate/SKILL.md', segments: ['ideate', 'SKILL.md'] },
  {
    id: 'ideate/references/constraint-anchoring.md',
    segments: ['ideate', 'references', 'constraint-anchoring.md'],
  },
  { id: 'refactor/SKILL.md', segments: ['refactor', 'SKILL.md'] },
  {
    id: 'refactor/references/brief-template.md',
    segments: ['refactor', 'references', 'brief-template.md'],
  },
  {
    id: 'refactor/references/overhaul-track.md',
    segments: ['refactor', 'references', 'overhaul-track.md'],
  },
  {
    id: 'refactor/references/polish-track.md',
    segments: ['refactor', 'references', 'polish-track.md'],
  },
  { id: 'shepherd/SKILL.md', segments: ['shepherd', 'SKILL.md'] },
];

describe('catalog-registration gating lint (DR-33)', () => {
  it.each(AFFECTED_FILES)(
    'SkillsSrc_$id_NoRetiredDevCatalogFlag',
    ({ segments }) => {
      const content = readFileSync(join(SKILLS_SRC, ...segments), 'utf8');
      expect(content).not.toMatch(/devCatalog/i);
    },
  );

  it.each(AFFECTED_FILES)(
    'SkillsSrc_$id_ExpressesCatalogRegistrationGate',
    ({ segments }) => {
      const content = readFileSync(join(SKILLS_SRC, ...segments), 'utf8');
      expect(content).toMatch(CATALOG_REGISTRATION_RE);
    },
  );
});
